services:
  app:
    image: lucasvavon/auth-sample-app:latest
    container_name: auth-sample-app
    environment:
      DATABASE_URL: "postgresql://admin:admin@db:5432/myapp"
    ports:
      - "1323:1323"


  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth-sample-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
